### ISSUE TITLE
SLR project wizard should allow to create empty bibtex/taxonomy files

### ISSUE THREAD

**Issue by lschuetze** [sebastiangoetz/slr-toolkit#11]
Currently you can only load existing taxonomy or bibtex files. There are wizards that allow to create empty taxonomy or bibtex files but that need an existing project. They should be reused if the user have no prepared taxonomy or bibtex files.

**Comment by lschuetze** [comment]
The import wizards need to be rewritten to fully solve this issue.

**Comment by jasper-d** [comment]
Fixed in b67f9bf

Some more work needed though c.f. #26
