### ISSUE TITLE
Ship JRE with the toolkit or migrate to a more recent version of Java

### ISSUE THREAD

**Issue by andreasdomanowski** [sebastiangoetz/slr-toolkit#130]
The SLR toolkit runs on Java 8 and is partially incompatible with more recent versions (e.g. https://github.com/sebastiangoetz/slr-toolkit/issues/129; Java 11). Since there are two more up-to-date LTS versions of Java, it may be wise to migrate. If that is not desirable, the toolkit should be shipped with JRE8.

Concerning the latter, legal implications regarding the license would need to be clarified. Furthermore, if the toolkit should stay slim and additionally an upgrade to a more recent version of Java is desired as well as shipping it with a JRE, it needs to be assessed how well OSGi works with `jlink`.

**Comment by sebastiangoetz** [comment]
the new release now runs on JDK17+
