### ISSUE TITLE
Feature Request: CSV Export

### ISSUE THREAD

**Issue by sebastiangoetz** [sebastiangoetz/slr-toolkit#20]
The data visualized using the current diagrams should be exportable as CSV.

**Comment by lschuetze** [comment]
This would be very helpful because it allows to use different toolings more specialized in visualization (e.g., tikz, gnuplot, R)

**Comment by pibebtol** [comment]
This is gonna be in an upcoming release.
Probably in a few (2 to 4) months from now.

**Comment by sebastiangoetz** [comment]
Now supported in [release 0.2.8](https://github.com/sebastiangoetz/slr-toolkit/releases/tag/0.2.8)
