### ISSUE TITLE
Perspective is out of sync with current development

### ISSUE THREAD

**Issue by lschuetze** [sebastiangoetz/slr-toolkit#4]
The perspective needs some love and has to be adopted to the newly created (and upcoming) views.

- [x] Fix perspective
    - [x] Open taxonomy editor in lower right corner. _Editors are always opened in the editor area and there can't be more than one editor area -> can't/won't implement_
- [x] Fix menus
    - [x] Add standard file menu and wizards etc.
    - [x] Remove "Run" menu (probably added by dependencies on org.eclipse.debug.ui
    - [x] Disable Wizards for projects / file types that are not applicable to SLR (e.g. EMF projects)

**Comment by jasper-d** [comment]
Hiding the "Run" menu using an extension point as described [here](http://codeandme.blogspot.de/2011/09/hiding-ui-elements-in-rcp.html) doesn't work.
Calling hideActionSet("...") doesn't work either.
