### ISSUE TITLE
Check if multiple bibtex files in one project are supported

### ISSUE THREAD

**Issue by jasper-d** [sebastiangoetz/slr-toolkit#50]
... and fix if not

**Comment by jasper-d** [comment]
Comment says no: https://github.com/sebastiangoetz/slr-toolkit/blob/9f6299b29cb1c9867a4aa2dc7bd93d2bca58d79a/plugins/de.tudresden.slr.ui.chart/src/de/tudresden/slr/ui/chart/logic/ChartDataProvider.java#L90

**Comment by sebastiangoetz** [comment]
using multiple bibtex files works fine
