### ISSUE TITLE
Eclipse requests to add XText nature upon taxonomy file creation

### ISSUE THREAD

**Issue by lschuetze** [sebastiangoetz/slr-toolkit#6]
The user is asked if the project should be changed to a Xtext project when a taxonomy file is created. This should be done automatically w/o asking the user. Otherwise, it may confuse the user.

**Comment by jasper-d** [comment]
Should be fixed with e28a2a3, requires confirmation

**Comment by jasper-d** [comment]
Not fixed in feature/app
