### ISSUE TITLE
Remove .java._trace and .xtendbin files from the repository

### ISSUE THREAD

**Issue by jasper-d** [sebastiangoetz/slr-toolkit#69]
These files are generated by XText but should not be tracked in git.

Removing these requires to filter the whole tree and then adding them to .gitignore, e.g. `git filter-branch --tree-filter "git rm -rf --ignore-unmatch *.xtendbin" --prune-empty -- --all`.
This will rewrite most of the git history though (use with care).

**Comment by sebastiangoetz** [comment]
fixed manually
